[build]
  command = "touch .env && if [ ! -d \"flutter\" ]; then git clone https://github.com/flutter/flutter.git -b stable --depth 1; fi && ./flutter/bin/flutter build web --release --dart-define=SUPABASE_URL=\"$MY_SUPABASE_URL\" --dart-define=SUPABASE_ANON=\"$ANON\""
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
